"""Field-level collection activities and deterministic parser contracts."""

from __future__ import annotations

from dataclasses import dataclass

from smart_money.research.contracts import MarketArchetype


@dataclass(frozen=True)
class ContractActivityRecipe:
    extractor_family: str
    domain: str
    supported_fields: frozenset[str]
    parser_id: str = "contract-fields.generic.v1"
    budget_cost: int = 1
    cache_ttl_seconds: int = 300
    min_interval_seconds: float = 2.0
    max_attempts: int = 2


CONTRACT_ACTIVITY_RECIPES: dict[str, ContractActivityRecipe] = {
    "MACRO_FED_DECISION_BOARD": ContractActivityRecipe(
        extractor_family="MACRO",
        domain="MACRO_ECONOMY",
        supported_fields=frozenset(
            {
                "current_policy_range",
                "exact_meeting_time",
                "market_implied_policy_distribution",
                "official_speaker_timeline",
            }
        ),
        parser_id="macro.fed-decision.v1",
    ),
    "MACRO_RELEASE_CALENDAR": ContractActivityRecipe(
        extractor_family="MACRO",
        domain="MACRO_ECONOMY",
        supported_fields=frozenset({"pending_data_before_decision"}),
        parser_id="macro.release-calendar.v1",
    ),
    "FINANCE_IPO_FILING_SOURCE": ContractActivityRecipe(
        extractor_family="FINANCE",
        domain="FINANCE",
        supported_fields=frozenset(
            {
                "issuer_identity",
                "official_filing_status",
                "exchange_or_regulator_source",
                "remaining_conditions",
            }
        ),
        parser_id="finance.sec-ipo.v1",
        cache_ttl_seconds=900,
    ),
    "POLITICS_ENTITY_STATUS": ContractActivityRecipe(
        extractor_family="POLITICS",
        domain="POLITICS_ELECTIONS",
        supported_fields=frozenset({"political_entities", "jurisdiction", "actor_status"}),
        parser_id="politics.generic.v1",
    ),
    "POLITICS_OFFICIAL_PROCESS": ContractActivityRecipe(
        extractor_family="POLITICS",
        domain="POLITICS_ELECTIONS",
        supported_fields=frozenset({"official_process", "official_timeline", "official_statements"}),
        parser_id="politics.generic.v1",
    ),
    "POLITICS_POLLING": ContractActivityRecipe(
        extractor_family="POLITICS",
        domain="POLITICS_ELECTIONS",
        supported_fields=frozenset({"polling_snapshot"}),
        parser_id="politics.generic.v1",
        cache_ttl_seconds=900,
    ),
    "POLITICS_ACCOUNTABILITY": ContractActivityRecipe(
        extractor_family="POLITICS",
        domain="POLITICS_ELECTIONS",
        supported_fields=frozenset({"campaign_finance_snapshot", "court_or_legal_status"}),
        parser_id="politics.generic.v1",
        cache_ttl_seconds=900,
    ),
    "TECH_PRODUCT_OFFICIAL_SOURCE": ContractActivityRecipe(
        extractor_family="TECH",
        domain="TECH_SCIENCE",
        supported_fields=frozenset({"official_product_status", "latest_official_statement", "remaining_milestones"}),
        parser_id="tech.official-release.v1",
        cache_ttl_seconds=900,
    ),
    "TECH_PRODUCT_TESTING_SOURCE": ContractActivityRecipe(
        extractor_family="TECH",
        domain="TECH_SCIENCE",
        supported_fields=frozenset({"credible_leak_or_testing_evidence"}),
        parser_id="tech.testing-signal.v1",
        cache_ttl_seconds=900,
    ),
    "GEOPOLITICS_EVENT_CONTEXT": ContractActivityRecipe(
        extractor_family="GEOPOLITICS",
        domain="GEOPOLITICS",
        supported_fields=frozenset({"actor_and_target_identity", "geographic_scope"}),
        parser_id="geopolitics.event-context.v1",
    ),
    "GEOPOLITICS_PRIMARY_CONFIRMATION": ContractActivityRecipe(
        extractor_family="GEOPOLITICS",
        domain="GEOPOLITICS",
        supported_fields=frozenset({"independent_primary_confirmation"}),
        parser_id="geopolitics.primary-confirmation.v1",
    ),
    "SPORTS_FIXTURE_SCOREBOARD": ContractActivityRecipe(
        extractor_family="SPORTS",
        domain="SPORTS",
        supported_fields=frozenset({"exact_fixture_identity", "scheduled_start_time", "official_scoreboard"}),
        parser_id="sports.fixture-scoreboard.v1",
        cache_ttl_seconds=120,
        max_attempts=1,
    ),
    "SPORTS_ROSTER_AVAILABILITY": ContractActivityRecipe(
        extractor_family="SPORTS",
        domain="SPORTS",
        supported_fields=frozenset({"roster_or_lineup", "injury_or_availability"}),
        parser_id="sports.roster-availability.v1",
        cache_ttl_seconds=120,
        max_attempts=1,
    ),
    "SPORTS_MARKET_ODDS": ContractActivityRecipe(
        extractor_family="SPORTS",
        domain="SPORTS",
        supported_fields=frozenset({"market_odds_snapshot"}),
        parser_id="sports.market-odds.v1",
        cache_ttl_seconds=120,
        max_attempts=1,
    ),
    "ESPORTS_SERIES_INTELLIGENCE": ContractActivityRecipe(
        extractor_family="ESPORTS",
        domain="ESPORTS",
        supported_fields=frozenset(
            {
                "exact_series_identity",
                "best_of_format",
                "scheduled_start_time",
                "official_scoreboard",
                "roster_and_substitutions",
                "patch_or_map_context",
            }
        ),
        parser_id="esports.series.v1",
        cache_ttl_seconds=120,
        max_attempts=1,
    ),
}


# Crypto capabilities are shared by one CryptoAgent.  The activity boundary is
# case-agnostic: contracts compose the fields they need from these registered
# deterministic capabilities instead of creating a new agent per market title.
CONTRACT_ACTIVITY_RECIPES.update(
    {
        "CRYPTO_RESOLUTION_RULES": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset(
                {
                    "asset_identity",
                    "exact_window_start",
                    "exact_window_end",
                    "window_timezone",
                    "resolution_price_source",
                    "resolution_pair",
                    "threshold",
                    "comparison_operator",
                    "window_start",
                    "window_end",
                    "endpoint_time",
                    "endpoint_timezone",
                    "resolution_source",
                    "deadline",
                    "launch_definition",
                    "transferability_requirement",
                    "tradability_requirement",
                    "qualifying_action_definition",
                    "sale_definition",
                    "event_definition",
                    "resolution_definition",
                    "market_predicate",
                }
            ),
            parser_id="crypto.resolution-rules.v1",
            budget_cost=0,
            min_interval_seconds=0,
        ),
        "CRYPTO_PRICE_WINDOW": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset(
                {
                    "start_price",
                    "end_price",
                    "minute_or_finer_path",
                    "window_high",
                    "window_low",
                    "realized_window_return",
                    "realized_window_volatility",
                    "calculation_status",
                    "endpoint_price",
                    "distance_to_threshold",
                    "volatility_to_endpoint",
                    "scenario_distribution",
                    "data_status",
                }
            ),
            parser_id="crypto.price-window.v1",
            cache_ttl_seconds=30,
            min_interval_seconds=1,
        ),
        "CRYPTO_THRESHOLD_PATH": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset(
                {
                    "current_price",
                    "distance_to_threshold",
                    "window_high",
                    "window_low",
                    "threshold_hit",
                    "threshold_hit_at",
                    "minute_path_coverage",
                    "realized_volatility",
                    "remaining_time",
                }
            ),
            parser_id="crypto.threshold-path.v1",
            cache_ttl_seconds=60,
        ),
        "CRYPTO_SPOT_SNAPSHOT": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset({"current_price", "spot_price_at_measurement", "price_source"}),
            parser_id="crypto.spot.v1",
            cache_ttl_seconds=30,
        ),
        "CRYPTO_DERIVATIVES_STATE": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset({"funding_snapshot"}),
            parser_id="crypto.derivatives.v1",
            cache_ttl_seconds=120,
        ),
        "CRYPTO_ETF_FLOW": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset({"etf_flow_snapshot"}),
            parser_id="crypto.etf-flow.v1",
            cache_ttl_seconds=900,
        ),
        "CRYPTO_LIQUIDATION_STATE": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset({"liquidation_snapshot"}),
            parser_id="crypto.liquidations.v1",
            cache_ttl_seconds=120,
        ),
        "CRYPTO_TOKEN_OFFICIAL_STATUS": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset(
                {
                    "project_identity",
                    "official_token_name",
                    "official_token_status",
                    "official_announcement",
                    "contract_address_status",
                    "claim_status",
                    "remaining_milestones",
                    "official_project_announcement",
                    "sale_start",
                    "sale_end",
                    "eligibility",
                    "sale_status",
                    "official_status",
                    "effective_time",
                    "remaining_conditions",
                    "event_state",
                }
            ),
            parser_id="crypto.project-official.v1",
            cache_ttl_seconds=600,
        ),
        "CRYPTO_TOKEN_SUPPLY": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset(
                {
                    "project_identity",
                    "token_identity",
                    "total_supply",
                    "circulating_supply",
                    "supply_source",
                    "tge_time",
                    "measurement_time",
                    "measurement_timezone",
                    "calculated_fdv",
                    "fdv_threshold",
                    "threshold_status",
                    "calculation_formula",
                    "source_consistency",
                }
            ),
            parser_id="crypto.token-supply.v1",
            cache_ttl_seconds=600,
        ),
        "CRYPTO_PREMARKET_PRICE": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset({"premarket_price"}),
            parser_id="crypto.premarket.v1",
            cache_ttl_seconds=120,
        ),
        "CRYPTO_EXCHANGE_LISTING": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset(
                {
                    "exchange_listings",
                    "exchange_listing_status",
                    "token_identity",
                    "exchange_identity",
                    "official_exchange_announcement",
                    "deposit_open_time",
                    "trading_open_time",
                    "withdrawal_open_time",
                    "spot_or_derivatives",
                    "listing_status",
                }
            ),
            parser_id="crypto.exchange-listing.v1",
            cache_ttl_seconds=300,
        ),
        "CRYPTO_SEC_FILINGS": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset(
                {
                    "sec_filing_status",
                    "sec_filing_ids",
                    "official_holdings",
                    "official_holdings_as_of",
                    "official_holdings_before",
                    "confirmed_sale",
                }
            ),
            parser_id="crypto.sec-filings.v1",
            cache_ttl_seconds=900,
        ),
        "CRYPTO_COMPANY_TREASURY": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset(
                {
                    "company_identity",
                    "official_company_statement",
                    "official_holdings",
                    "official_holdings_as_of",
                    "cash_reserve",
                    "debt_obligations",
                    "preferred_dividend_obligations",
                    "financing_capacity",
                    "liquidity_pressure_indicators",
                    "remaining_conditions",
                    "confirmed_sale",
                    "official_sale_disclosure",
                }
            ),
            parser_id="crypto.company-treasury.v1",
            cache_ttl_seconds=900,
        ),
        "CRYPTO_ONCHAIN_TREASURY_FLOW": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset({"onchain_transfers", "custody_destination"}),
            parser_id="crypto.onchain-treasury.v1",
            cache_ttl_seconds=120,
            min_interval_seconds=0,
        ),
        "CRYPTO_REGULATORY_PROCESS": ContractActivityRecipe(
            extractor_family="CRYPTO",
            domain="CRYPTO",
            supported_fields=frozenset(
                {
                    "jurisdiction",
                    "regulator_or_legislature",
                    "instrument",
                    "current_stage",
                    "official_text",
                    "official_timeline",
                    "next_procedural_step",
                    "deadline",
                    "court_status",
                }
            ),
            parser_id="crypto.regulatory-process.v1",
            cache_ttl_seconds=900,
        ),
    }
)


FIELD_ACTIVITY_BINDINGS: dict[MarketArchetype, dict[str, tuple[str, ...]]] = {
    MarketArchetype.CENTRAL_BANK_DECISION: {
        "current_policy_range": ("MACRO_FED_DECISION_BOARD",),
        "exact_meeting_time": ("MACRO_FED_DECISION_BOARD",),
        "resolution_definition": ("RULES_RESOLUTION_SOURCE",),
        "latest_inflation_release": ("MACRO_BLS_RELEASES",),
        "latest_labor_release": ("MACRO_BLS_RELEASES",),
        "market_implied_policy_distribution": ("MACRO_FED_DECISION_BOARD",),
        "official_speaker_timeline": ("MACRO_FED_DECISION_BOARD",),
        "pending_data_before_decision": ("MACRO_RELEASE_CALENDAR",),
    },
    MarketArchetype.PRODUCT_RELEASE_BY_DATE: {
        "exact_definition_of_release": ("RULES_RESOLUTION_SOURCE",),
        "deadline_and_timezone": ("RULES_RESOLUTION_SOURCE",),
        "official_product_status": ("TECH_PRODUCT_OFFICIAL_SOURCE",),
        "latest_official_statement": ("TECH_PRODUCT_OFFICIAL_SOURCE",),
        "credible_leak_or_testing_evidence": ("TECH_PRODUCT_TESTING_SOURCE",),
        "remaining_milestones": ("TECH_PRODUCT_OFFICIAL_SOURCE",),
        "related_deadline_markets": ("RELATED_MARKET_CONTEXT",),
    },
    MarketArchetype.EXACT_WEATHER_BUCKET: {
        "station_identity": ("WEATHER_REGISTERED_DATA",),
        "exact_bucket_definition": ("RULES_RESOLUTION_SOURCE",),
        "settlement_observation_source": ("RULES_RESOLUTION_SOURCE",),
        "forecast_distribution": ("WEATHER_REGISTERED_DATA",),
        "forecast_horizon": ("WEATHER_REGISTERED_DATA",),
        "observation_timezone": ("RULES_RESOLUTION_SOURCE",),
    },
    MarketArchetype.WEATHER_THRESHOLD: {
        "location_identity": ("WEATHER_REGISTERED_DATA",),
        "threshold_definition": ("RULES_RESOLUTION_SOURCE",),
        "settlement_observation_source": ("RULES_RESOLUTION_SOURCE",),
        "forecast_distribution": ("WEATHER_REGISTERED_DATA",),
        "forecast_horizon": ("WEATHER_REGISTERED_DATA",),
    },
    MarketArchetype.PRICE_DIRECTION_SHORT_WINDOW: {
        "comparison_operator": ("CRYPTO_RESOLUTION_RULES",),
        "asset_identity": ("CRYPTO_RESOLUTION_RULES",),
        "exact_window_start": ("CRYPTO_RESOLUTION_RULES",),
        "exact_window_end": ("CRYPTO_RESOLUTION_RULES",),
        "window_timezone": ("CRYPTO_RESOLUTION_RULES",),
        "resolution_price_source": ("CRYPTO_RESOLUTION_RULES",),
        "resolution_pair": ("CRYPTO_RESOLUTION_RULES",),
        "start_price": ("CRYPTO_PRICE_WINDOW",),
        "end_price": ("CRYPTO_PRICE_WINDOW",),
        "minute_or_finer_path": ("CRYPTO_PRICE_WINDOW",),
        "window_high": ("CRYPTO_PRICE_WINDOW",),
        "window_low": ("CRYPTO_PRICE_WINDOW",),
        "realized_window_return": ("CRYPTO_PRICE_WINDOW",),
        "realized_window_volatility": ("CRYPTO_PRICE_WINDOW",),
        "calculation_status": ("CRYPTO_PRICE_WINDOW",),
    },
    MarketArchetype.PRICE_THRESHOLD_TOUCH: {
        "asset_identity": ("CRYPTO_RESOLUTION_RULES",),
        "threshold": ("CRYPTO_RESOLUTION_RULES",),
        "comparison_operator": ("CRYPTO_RESOLUTION_RULES",),
        "window_start": ("CRYPTO_RESOLUTION_RULES",),
        "window_end": ("CRYPTO_RESOLUTION_RULES",),
        "resolution_price_source": ("CRYPTO_RESOLUTION_RULES",),
        "current_price": ("CRYPTO_THRESHOLD_PATH",),
        "distance_to_threshold": ("CRYPTO_THRESHOLD_PATH",),
        "window_high": ("CRYPTO_THRESHOLD_PATH",),
        "window_low": ("CRYPTO_THRESHOLD_PATH",),
        "threshold_hit": ("CRYPTO_THRESHOLD_PATH",),
        "threshold_hit_at": ("CRYPTO_THRESHOLD_PATH",),
        "minute_path_coverage": ("CRYPTO_THRESHOLD_PATH",),
        "realized_volatility": ("CRYPTO_THRESHOLD_PATH",),
        "remaining_time": ("CRYPTO_THRESHOLD_PATH",),
        "etf_flow_snapshot": ("CRYPTO_ETF_FLOW",),
        "funding_snapshot": ("CRYPTO_DERIVATIVES_STATE",),
        "liquidation_snapshot": ("CRYPTO_LIQUIDATION_STATE",),
    },
    MarketArchetype.PRICE_THRESHOLD_ENDPOINT: {
        "threshold": ("CRYPTO_RESOLUTION_RULES",),
        "comparison_operator": ("CRYPTO_RESOLUTION_RULES",),
        "endpoint_time": ("CRYPTO_RESOLUTION_RULES",),
        "endpoint_timezone": ("CRYPTO_RESOLUTION_RULES",),
        "resolution_source": ("CRYPTO_RESOLUTION_RULES",),
        "endpoint_price": ("CRYPTO_PRICE_WINDOW",),
        "current_price": ("CRYPTO_SPOT_SNAPSHOT",),
        "distance_to_threshold": ("CRYPTO_PRICE_WINDOW",),
        "volatility_to_endpoint": ("CRYPTO_PRICE_WINDOW",),
        "scenario_distribution": ("CRYPTO_PRICE_WINDOW",),
        "data_status": ("CRYPTO_PRICE_WINDOW",),
    },
    MarketArchetype.CRYPTO_TOKEN_LAUNCH: {
        "project_identity": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "official_token_name": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "launch_definition": ("CRYPTO_RESOLUTION_RULES",),
        "transferability_requirement": ("CRYPTO_RESOLUTION_RULES",),
        "tradability_requirement": ("CRYPTO_RESOLUTION_RULES",),
        "deadline": ("CRYPTO_RESOLUTION_RULES",),
        "official_token_status": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "official_announcement": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "contract_address_status": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "claim_status": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "exchange_listing_status": ("CRYPTO_EXCHANGE_LISTING",),
        "remaining_milestones": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
    },
    MarketArchetype.CRYPTO_FDV_AFTER_LAUNCH: {
        "comparison_operator": ("CRYPTO_RESOLUTION_RULES",),
        "project_identity": ("CRYPTO_TOKEN_SUPPLY",),
        "token_identity": ("CRYPTO_TOKEN_SUPPLY",),
        "total_supply": ("CRYPTO_TOKEN_SUPPLY",),
        "circulating_supply": ("CRYPTO_TOKEN_SUPPLY",),
        "supply_source": ("CRYPTO_TOKEN_SUPPLY",),
        "tge_time": ("CRYPTO_TOKEN_SUPPLY",),
        "measurement_time": ("CRYPTO_TOKEN_SUPPLY",),
        "measurement_timezone": ("CRYPTO_TOKEN_SUPPLY",),
        "price_source": ("CRYPTO_SPOT_SNAPSHOT",),
        "premarket_price": ("CRYPTO_PREMARKET_PRICE",),
        "spot_price_at_measurement": ("CRYPTO_SPOT_SNAPSHOT",),
        "exchange_listings": ("CRYPTO_EXCHANGE_LISTING",),
        "calculated_fdv": ("CRYPTO_TOKEN_SUPPLY",),
        "fdv_threshold": ("CRYPTO_TOKEN_SUPPLY",),
        "threshold_status": ("CRYPTO_TOKEN_SUPPLY",),
        "calculation_formula": ("CRYPTO_TOKEN_SUPPLY",),
        "source_consistency": ("CRYPTO_TOKEN_SUPPLY",),
    },
    MarketArchetype.CRYPTO_CORPORATE_BTC_ACTION: {
        "company_identity": ("CRYPTO_COMPANY_TREASURY",),
        "qualifying_action_definition": ("CRYPTO_RESOLUTION_RULES",),
        "deadline": ("CRYPTO_RESOLUTION_RULES",),
        "official_holdings": ("CRYPTO_SEC_FILINGS",),
        "official_holdings_as_of": ("CRYPTO_SEC_FILINGS",),
        "sec_filing_status": ("CRYPTO_SEC_FILINGS",),
        "sec_filing_ids": ("CRYPTO_SEC_FILINGS",),
        "official_company_statement": ("CRYPTO_COMPANY_TREASURY",),
        "onchain_transfers": ("CRYPTO_ONCHAIN_TREASURY_FLOW",),
        "custody_destination": ("CRYPTO_ONCHAIN_TREASURY_FLOW",),
        "confirmed_sale": ("CRYPTO_COMPANY_TREASURY", "CRYPTO_SEC_FILINGS"),
        "cash_reserve": ("CRYPTO_COMPANY_TREASURY",),
        "debt_obligations": ("CRYPTO_COMPANY_TREASURY",),
        "preferred_dividend_obligations": ("CRYPTO_COMPANY_TREASURY",),
        "financing_capacity": ("CRYPTO_COMPANY_TREASURY",),
        "liquidity_pressure_indicators": ("CRYPTO_COMPANY_TREASURY",),
        "remaining_conditions": ("CRYPTO_COMPANY_TREASURY",),
        "official_sale_disclosure": ("CRYPTO_COMPANY_TREASURY",),
        "official_holdings_before": ("CRYPTO_SEC_FILINGS",),
    },
    MarketArchetype.CRYPTO_REGULATION: {
        "jurisdiction": ("CRYPTO_REGULATORY_PROCESS",),
        "regulator_or_legislature": ("CRYPTO_REGULATORY_PROCESS",),
        "instrument": ("CRYPTO_REGULATORY_PROCESS",),
        "current_stage": ("CRYPTO_REGULATORY_PROCESS",),
        "official_text": ("CRYPTO_REGULATORY_PROCESS",),
        "official_timeline": ("CRYPTO_REGULATORY_PROCESS",),
        "next_procedural_step": ("CRYPTO_REGULATORY_PROCESS",),
        "deadline": ("CRYPTO_REGULATORY_PROCESS",),
        "court_status": ("CRYPTO_REGULATORY_PROCESS",),
        "resolution_definition": ("CRYPTO_RESOLUTION_RULES",),
    },
    MarketArchetype.CRYPTO_EXCHANGE_LISTING: {
        "token_identity": ("CRYPTO_EXCHANGE_LISTING",),
        "exchange_identity": ("CRYPTO_EXCHANGE_LISTING",),
        "official_exchange_announcement": ("CRYPTO_EXCHANGE_LISTING",),
        "official_project_announcement": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "deposit_open_time": ("CRYPTO_EXCHANGE_LISTING",),
        "trading_open_time": ("CRYPTO_EXCHANGE_LISTING",),
        "withdrawal_open_time": ("CRYPTO_EXCHANGE_LISTING",),
        "spot_or_derivatives": ("CRYPTO_EXCHANGE_LISTING",),
        "listing_status": ("CRYPTO_EXCHANGE_LISTING",),
    },
    MarketArchetype.CRYPTO_PUBLIC_SALE: {
        "project_identity": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "sale_definition": ("CRYPTO_RESOLUTION_RULES",),
        "official_announcement": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "sale_start": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "sale_end": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "eligibility": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "sale_status": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "resolution_definition": ("CRYPTO_RESOLUTION_RULES",),
    },
    MarketArchetype.CRYPTO_PROTOCOL_EVENT: {
        "project_identity": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "event_definition": ("CRYPTO_RESOLUTION_RULES",),
        "official_status": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "effective_time": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "remaining_conditions": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
        "resolution_definition": ("CRYPTO_RESOLUTION_RULES",),
    },
    MarketArchetype.GENERAL_CRYPTO: {
        "asset_identity": ("CRYPTO_RESOLUTION_RULES",),
        "market_predicate": ("CRYPTO_RESOLUTION_RULES",),
        "resolution_definition": ("CRYPTO_RESOLUTION_RULES",),
        "event_state": ("CRYPTO_TOKEN_OFFICIAL_STATUS",),
    },
    MarketArchetype.SPORTS_MATCH_WINNER: {
        "exact_fixture_identity": ("SPORTS_FIXTURE_SCOREBOARD",),
        "scheduled_start_time": ("SPORTS_FIXTURE_SCOREBOARD",),
        "official_scoreboard": ("SPORTS_FIXTURE_SCOREBOARD",),
        "roster_or_lineup": ("SPORTS_ROSTER_AVAILABILITY",),
        "injury_or_availability": ("SPORTS_ROSTER_AVAILABILITY",),
        "market_odds_snapshot": ("SPORTS_MARKET_ODDS",),
        "resolution_definition": ("RULES_RESOLUTION_SOURCE",),
    },
    MarketArchetype.ESPORTS_MATCH_WINNER: {
        "exact_series_identity": ("ESPORTS_SERIES_INTELLIGENCE",),
        "best_of_format": ("ESPORTS_SERIES_INTELLIGENCE",),
        "scheduled_start_time": ("ESPORTS_SERIES_INTELLIGENCE",),
        "official_scoreboard": ("ESPORTS_SERIES_INTELLIGENCE",),
        "roster_and_substitutions": ("ESPORTS_SERIES_INTELLIGENCE",),
        "patch_or_map_context": ("ESPORTS_SERIES_INTELLIGENCE",),
        "resolution_definition": ("RULES_RESOLUTION_SOURCE",),
    },
    MarketArchetype.IPO_COMPLETION: {
        "issuer_identity": ("FINANCE_IPO_FILING_SOURCE",),
        "completion_definition": ("RULES_RESOLUTION_SOURCE",),
        "deadline_and_timezone": ("RULES_RESOLUTION_SOURCE",),
        "official_filing_status": ("FINANCE_IPO_FILING_SOURCE",),
        "exchange_or_regulator_source": ("FINANCE_IPO_FILING_SOURCE",),
        "remaining_conditions": ("FINANCE_IPO_FILING_SOURCE",),
    },
    MarketArchetype.ELECTION_WINNER: {
        "political_entities": ("POLITICS_ENTITY_STATUS",),
        "jurisdiction": ("POLITICS_ENTITY_STATUS",),
        "official_process": ("POLITICS_OFFICIAL_PROCESS",),
        "actor_status": ("POLITICS_ENTITY_STATUS",),
        "official_timeline": ("POLITICS_OFFICIAL_PROCESS",),
        "polling_snapshot": ("POLITICS_POLLING",),
        "campaign_finance_snapshot": ("POLITICS_ACCOUNTABILITY",),
        "court_or_legal_status": ("POLITICS_ACCOUNTABILITY",),
        "resolution_definition": ("RULES_RESOLUTION_SOURCE",),
    },
    MarketArchetype.APPOINTMENT_OR_REMOVAL: {
        "political_entities": ("POLITICS_ENTITY_STATUS",),
        "jurisdiction": ("POLITICS_ENTITY_STATUS",),
        "official_process": ("POLITICS_OFFICIAL_PROCESS",),
        "actor_status": ("POLITICS_ENTITY_STATUS",),
        "official_timeline": ("POLITICS_OFFICIAL_PROCESS",),
        "official_statements": ("POLITICS_OFFICIAL_PROCESS",),
        "court_or_legal_status": ("POLITICS_ACCOUNTABILITY",),
        "resolution_definition": ("RULES_RESOLUTION_SOURCE",),
    },
    MarketArchetype.POLITICAL_EXECUTIVE_ACTION: {
        "political_entities": ("POLITICS_ENTITY_STATUS",),
        "jurisdiction": ("POLITICS_ENTITY_STATUS",),
        "official_process": ("POLITICS_OFFICIAL_PROCESS",),
        "actor_status": ("POLITICS_ENTITY_STATUS",),
        "official_timeline": ("POLITICS_OFFICIAL_PROCESS",),
        "official_statements": ("POLITICS_OFFICIAL_PROCESS",),
        "court_or_legal_status": ("POLITICS_ACCOUNTABILITY",),
        "resolution_definition": ("RULES_RESOLUTION_SOURCE",),
    },
    MarketArchetype.POLITICAL_PARTY_CONTROL: {
        "political_entities": ("POLITICS_ENTITY_STATUS",),
        "jurisdiction": ("POLITICS_ENTITY_STATUS",),
        "official_process": ("POLITICS_OFFICIAL_PROCESS",),
        "actor_status": ("POLITICS_ENTITY_STATUS",),
        "official_timeline": ("POLITICS_OFFICIAL_PROCESS",),
        "polling_snapshot": ("POLITICS_POLLING",),
        "resolution_definition": ("RULES_RESOLUTION_SOURCE",),
    },
    MarketArchetype.POLITICAL_POLLING: {
        "political_entities": ("POLITICS_ENTITY_STATUS",),
        "jurisdiction": ("POLITICS_ENTITY_STATUS",),
        "official_timeline": ("POLITICS_OFFICIAL_PROCESS",),
        "polling_snapshot": ("POLITICS_POLLING",),
        "resolution_definition": ("RULES_RESOLUTION_SOURCE",),
    },
    MarketArchetype.POLITICAL_INSTITUTIONAL_VOTE: {
        "political_entities": ("POLITICS_ENTITY_STATUS",),
        "jurisdiction": ("POLITICS_ENTITY_STATUS",),
        "official_process": ("POLITICS_OFFICIAL_PROCESS",),
        "actor_status": ("POLITICS_ENTITY_STATUS",),
        "official_timeline": ("POLITICS_OFFICIAL_PROCESS",),
        "official_statements": ("POLITICS_OFFICIAL_PROCESS",),
        "resolution_definition": ("RULES_RESOLUTION_SOURCE",),
    },
    MarketArchetype.POLITICAL_COURT_DECISION: {
        "political_entities": ("POLITICS_ENTITY_STATUS",),
        "jurisdiction": ("POLITICS_ENTITY_STATUS",),
        "official_process": ("POLITICS_OFFICIAL_PROCESS",),
        "official_timeline": ("POLITICS_OFFICIAL_PROCESS",),
        "official_statements": ("POLITICS_OFFICIAL_PROCESS",),
        "court_or_legal_status": ("POLITICS_ACCOUNTABILITY",),
        "resolution_definition": ("RULES_RESOLUTION_SOURCE",),
    },
    MarketArchetype.POLITICAL_LEGISLATION: {
        "political_entities": ("POLITICS_ENTITY_STATUS",),
        "jurisdiction": ("POLITICS_ENTITY_STATUS",),
        "official_process": ("POLITICS_OFFICIAL_PROCESS",),
        "actor_status": ("POLITICS_ENTITY_STATUS",),
        "official_timeline": ("POLITICS_OFFICIAL_PROCESS",),
        "official_statements": ("POLITICS_OFFICIAL_PROCESS",),
        "resolution_definition": ("RULES_RESOLUTION_SOURCE",),
    },
    MarketArchetype.MILITARY_ACTION: {
        "actor_and_target_identity": ("GEOPOLITICS_EVENT_CONTEXT",),
        "qualifying_action_definition": ("RULES_RESOLUTION_SOURCE",),
        "geographic_scope": ("GEOPOLITICS_EVENT_CONTEXT",),
        "deadline_and_timezone": ("RULES_RESOLUTION_SOURCE",),
        "independent_primary_confirmation": ("GEOPOLITICS_PRIMARY_CONFIRMATION",),
        "resolution_definition": ("RULES_RESOLUTION_SOURCE",),
    },
    MarketArchetype.MENTION_OR_POST_COUNT: {
        "speaker_identity": ("MENTIONS_REGISTERED_DATA",),
        "qualifying_mention_definition": ("RULES_RESOLUTION_SOURCE",),
        "counting_window": ("RULES_RESOLUTION_SOURCE",),
        "authoritative_transcript_or_feed": ("MENTIONS_REGISTERED_DATA",),
        "deduplication_rule": ("RULES_RESOLUTION_SOURCE",),
    },
}

# Extra treasury inputs support derived facts but are not mandatory evidence.
OPTIONAL_CONTRACT_FIELDS = {
    MarketArchetype.CRYPTO_CORPORATE_BTC_ACTION: {"official_holdings_before", "official_sale_disclosure"},
}

EVIDENCE_CONTRACTS: dict[MarketArchetype, tuple[str, ...]] = {
    archetype: tuple(field for field in bindings if field not in OPTIONAL_CONTRACT_FIELDS.get(archetype, set()))
    for archetype, bindings in FIELD_ACTIVITY_BINDINGS.items()
}
